### ISSUE TITLE
Prediction failed: [Errno 111] Connection refused

### ISSUE THREAD

**Issue by ziagit** [fofr/cog-comfyui-liveportrait#3]
**I try [fofr](https://replicate.com/fofr) / live-portrait but I get below errors**

Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 1348, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
File "/root/.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 1282, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 1328, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 1277, in endheaders
self._send_output(message_body, encode_chunked=encode_chunked)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 1037, in _send_output
self.send(msg)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 975, in send
self.connect()
File "/root/.pyenv/versions/3.10.6/lib/python3.10/http/client.py", line 941, in connect
self.sock = self._create_connection(
File "/root/.pyenv/versions/3.10.6/lib/python3.10/socket.py", line 845, in create_connection
raise err
File "/root/.pyenv/versions/3.10.6/lib/python3.10/socket.py", line 833, in create_connection
sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.6/lib/python3.10/site-packages/cog/server/worker.py", line 221, in _predict
result = predict(**payload)
File "/src/predict.py", line 132, in predict
self.comfyUI.cleanup(ALL_DIRECTORIES)
File "/src/comfyui.py", line 266, in cleanup
self.clear_queue()
File "/src/comfyui.py", line 159, in clear_queue
self.post_request("/queue", {"clear": True})
File "/src/comfyui.py", line 153, in post_request
with urllib.request.urlopen(req) as response:
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 216, in urlopen
return opener.open(url, data, timeout)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 519, in open
response = self._open(req, data)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 536, in _open
result = self._call_chain(self.handle_open, protocol, protocol +
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 496, in _call_chain
result = func(*args)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 1377, in http_open
return self.do_open(http.client.HTTPConnection, req)
File "/root/.pyenv/versions/3.10.6/lib/python3.10/urllib/request.py", line 1351, in do_open
raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

**Comment by nospam2k** [comment]
Same here, one day later

**Comment by teaguexiao** [comment]
same here, another day later
